# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
---
default: true
line_length: false
no-inline-html: false
no-trailing-punctuation: false
no-duplicate-heading: false
no-bare-urls: false
ol-prefix: false

# MD052/reference-links-images : Reference links and images should use a label that is defined : https://github.com/DavidAnson/markdownlint/blob/v0.37.4/doc/md052.md
MD052:
  # Include shortcut syntax
  shortcut_syntax: false